"use client";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import TopNav from "@/components/nav/TopNav";
import Top from "@/components/nav/Nav";
import Footer from "@/components/footer/Footer";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
import { usePathname } from "next/navigation";

import { Provider } from "react-redux";
import { store } from "./store";
export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <SessionProvider>
        <Provider store={store}>
          <body className={inter.className}>
            <ToastContainer />
            <TopNav />

            {!pathname.startsWith("/dashboard") && <Top />}
            {children}
            {!pathname.startsWith("/dashboard") && <Footer />}
          </body>
        </Provider>
      </SessionProvider>
    </html>
  );
}
